# Generated by Django 4.0 on 2023-05-26 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['city'], 'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
    ]
