# Generated by Django 4.0 on 2023-05-25 17:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_plate', models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator(message='Неверный формат номера', regex='^[1-9][0-9]{3}[A-Z]$')], verbose_name='Номер машины')),
                ('load_capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Грузоподъемность')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trucks', to='location.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'Грузовик',
                'verbose_name_plural': 'Грузовики',
            },
        ),
    ]
